name: reutiliza_cozinha
description: "Reutiliza & Cozinha"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: 1.0.6
  flutter_launcher_icons: 0.13.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^4.0.0
